name: Test suite

on:
  push:
  pull_request:
  schedule:
  - cron: 1 0 * * *  # Run daily at 0:01 UTC

jobs:
  tests:
    name: 👷
    runs-on: ${{ matrix.os }}
    strategy:
      # max-parallel: 5
      matrix:
        python-version:
        - 3.7
        - 3.6
        - 3.5
        - 2.7
        os:
        - ubuntu-18.04
        - ubuntu-16.04
        - macOS-10.14
        - windows-2019
        - windows-2016
        env:
        - TOXENV: python
        tox-addargs:
        - --use-venv -m unit
        - --use-venv -m integration -n auto --duration=5 -k "not test_install"
        - --use-venv -m integration -n auto --duration=5 -k "test_install"

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python-version }}
    - name: Install tox
      run: |
        python -m pip install --upgrade tox
    - name: 'Initialize tox envs: ${{ matrix.env.TOXENV }}'
      run: |
        python -m tox --parallel auto --notest
      env: ${{ matrix.env }}
    - name: Test with tox
      run: |
        python -m tox --parallel 0 -- ${{ matrix.tox-addargs }}
      env: ${{ matrix.env }}
